HOST = "irc.twitch.tv" #host to connect to, this should never change
PORT = 6667 #port to connect to, on restricted networks, try port 81
PASS = "oauth:xxxxxxxxxxxxxxxxxxxxxxx" #generate one here: twitchapps.com/tmi
NICK = "" #your bot's username, all lowercase
CHAN = "" #channel to connect to, all lowercase
OWNR = "" #the bot's owner (for future versions), all lowercase
WELC = "knubot has joined successfully" #a greeting message
GBYE = "knubot is disconnecting from chat" #a fairwell message
BAND = "Someone was BANNED" #shown when a user is banned
MODD = "Someone was MODDED" #shown when a user is modded
COMM = True #commands availablility
BANP = True #bannable phrases availability
POLL = True #polls are available
CSCO = False #command's case sensitivity
CSBN = False #bannable phrase's case sensitivity
CSPL = False #poll option's case sensitivity
PLEW = True #allow people to vote by typing in the exact option (number based voting is always an option)
PLCO = "!poll" #the command to view a poll
VTCO = "!vote" #the command to vote on a poll ("!command [option]")
NPMS = "No ongoing poll" #message to return if someone tries to view/vote on a poll when there isn't one